[package]
name = "mizer-node"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2021"

[features]
test = []

[dependencies]
anyhow = "1"
tracing = "0.1"
heck = "0.5"
serde = { version = "1", features = ["derive", "rc"] }
mizer-clock = { path = "../../clock" }
mizer-debug-ui = { path = "../../debug-ui" }
mizer-ports = { path = "../ports" }
mizer-injector = { path = "../../injector" }
mizer-util = { path = "../../../util" }
mizer-wgpu = { path = "../../wgpu" }
downcast = "0.11"
pinboard = "2.2"
enum-iterator = "2.0"
parking_lot = "0.12"
num_enum = "0.7"
uuid = { version = "1.11", features = ["v4", "serde"] }

[dev-dependencies]
test-case = "3.3"
