[package]
name = "mizer-vector-nodes"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
tracing = "0.1"
mizer-node = { path = "../../node" }
serde = { version = "1", features = ["derive"] }
enum-iterator = "1.5"
num_enum = "0.7"
mizer-wgpu = { path = "../../../wgpu" }
profiling = "1"
mizer-media = { path = "../../../../components/media" }
mizer-vector = { path = "../../../../components/vector" }
