[package]
name = "mizer-layout-queries"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
mizer-commander = { path = "../../commander" }
mizer-layouts = { path = ".." }
