[package]
name = "mizer-oscillator-nodes"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
log = "0.4"
mizer-node = { path = "../../../node" }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
test-case = "3.1"
