[package]
name = "mizer-dmx-nodes"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.82"
serde = { version = "1", features = ["derive"] }
mizer-node = { path = "../../../../node" }
mizer-protocol-dmx = { path = "../../../../../../components/connections/protocols/dmx" }
