[package]
name = "mizer-layouts"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
mizer-node = { path = "../pipeline/node" }
pinboard = "2.2"
base64 = "0.21"
