[package]
name = "mizer-g13"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
log = "0.4"
anyhow = "1"
g13 = "0.1"
futures = "0.3"
flume = "0.10"
pinboard = "2.1"
uuid = { version = "1.3", features = ["v4"] }
rusb = "*"
