[package]
name = "mizer-sequencer"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2021"

[features]
nightly = ["mockall/nightly"]

[dependencies]
anyhow = "1"
log = "0.4"
serde = { version = "1", features = ["derive"] }
mizer-module = { path = "../../runtime/module" }
mizer-fixtures = { path = "../fixtures" }
mizer-util = { path = "../../util" }
pinboard = "2.2"
profiling = "1"
dashmap = "5"
bezier-nd = "0.5"
geo-nd = "0.5"
itertools = "0.12"
num-traits = "0.2"
uuid = { version = "1.7", features = ["v4"] }
tracing = "0.1"
indexmap = "2.2"

[dev-dependencies]
test-case = "3.3"
mizer-util = { path = "../../util", features = ["test"] }
mockall = "0.11"
mockall_double = "0.3"
plotters = { version = "0.3", default-features = false, features = ["svg_backend", "line_series"] }
