[package]
name = "mizer-execution-planner"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
test-case = "3.3"
itertools = "0.12.1"
mizer-node = { path = "../pipeline/node" }
mizer-util = { path = "../../util" }
tracing = "0.1"
profiling = "1"
