[hotkeys.global]
view_1 = "f1"
view_2 = "f2"
view_3 = "f3"
view_4 = "f4"
view_5 = "f5"
view_6 = "f6"
view_7 = "f7"
view_8 = "f8"
view_9 = "f9"
view_10 = "f10"
view_11 = "f11"
view_12 = "f12"
programmer_pane = "shift+p"
selection_pane = "shift+s"
console_pane = "shift+c"
undo = "ctrl+z"
redo = "ctrl+shift+z"
open = "ctrl+o"
save = "ctrl+s"
save_as = "ctrl+shift+s"

[hotkeys.layouts]
add_layout = "alt+a"

[hotkeys.plan]
store = "insert"
highlight = "home"
clear = "backspace"

[hotkeys.programmer]
select_all = "ctrl+a"
clear = "backspace"
store = "insert"
highlight = "home"
assign_group = "ctrl+g"
next = "right"
prev = "left"
shuffle = "ctrl+r"

[hotkeys.patch]
add_fixture = "alt+a"
select_all = "ctrl+a"
clear = "backspace"
delete = "delete"
assign_group = "ctrl+g"

[hotkeys.nodes]
add_node = "alt+a"
duplicate_node = "ctrl+d"
group_nodes = "ctrl+g"
delete_node = "delete"
rename_node = "ctrl+r"

[hotkeys.sequencer]
add_sequence = "alt+a"
delete = "delete"
duplicate = "ctrl+d"
go_forward = "ctrl+g"
go_backward = "ctrl+shift+g"
stop = "alt+s"

[hotkeys.effects]
delete = "delete"
add_effect = "alt+a"

[hotkeys.media]
add_media = "alt+a"
delete = "delete"
