[package]
name = "mizer-nodes"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
tracing = "0.1"
serde = { version = "1", features = ["derive", "rc"] }
mizer-node = { path = "../node" }
mizer-audio-nodes = { path = "audio" }
mizer-clock-nodes = { path = "clock" }
mizer-color-nodes = { path = "behaviors/color" }
mizer-constant-nodes = { path = "behaviors/constants" }
mizer-conversion-nodes = { path = "behaviors/conversions" }
mizer-envelope-nodes = { path = "behaviors/envelope" }
mizer-oscillator-nodes = { path = "behaviors/oscillator" }
mizer-port-operation-nodes = { path = "behaviors/port-operations" }
mizer-dmx-nodes = { path = "connections/protocols/dmx" }
mizer-g13-nodes = { path = "connections/g13" }
mizer-gamepad-nodes = { path = "connections/gamepad" }
mizer-scripting-nodes = { path = "behaviors/scripting" }
mizer-step-sequencer-nodes = { path = "behaviors/step-sequencer" }
mizer-math-nodes = { path = "behaviors/math" }
mizer-sequencer-nodes = { path = "sequencer" }
mizer-fixture-nodes = { path = "fixture" }
mizer-laser-nodes = { path = "connections/laser" }
mizer-input-nodes = { path = "inputs" }
mizer-midi-nodes = { path = "connections/protocols/midi" }
mizer-mqtt-nodes = { path = "connections/protocols/mqtt" }
mizer-pixel-nodes = { path = "pixels" }
mizer-opc-nodes = { path = "connections/protocols/opc" }
mizer-osc-nodes = { path = "connections/protocols/osc" }
mizer-pro-dj-link-nodes = { path = "connections/protocols/pro-dj-link" }
mizer-video-nodes = { path = "video" }
mizer-ndi-nodes = { path = "video/ndi" }
mizer-screen-capture-nodes = { path = "video/screen-capture" }
mizer-surface-nodes = { path = "video/surfaces" }
mizer-text-nodes = { path = "video/text" }
mizer-webcam-nodes = { path = "video/webcams" }
mizer-data-nodes = { path = "data" }
mizer-plan-nodes = { path = "plan" }
mizer-timing-nodes = { path = "behaviors/timing" }
mizer-timecode-nodes = { path = "timecode" }
mizer-transport-nodes = { path = "transport" }
mizer-vector-nodes = { path = "vector" }
derive_more = "0.99"
dashmap = "5.5"

[dev-dependencies]
mizer-node = { path = "../node", features = ["test"] }
mizer-util = { path = "../../../util", features = ["test"] }
test-case = "3.3"
insta = "1.37"
plotters = { version = "0.3", default-features = false, features = ["svg_backend", "area_series"] }
