[package]
name = "mizer-g13-nodes"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
log = "0.4"
serde = { version = "1", features = ["derive"] }
mizer-g13 = { path = "../../../../../components/connections/devices/g13" }
mizer-devices = { path = "../../../../../components/connections/devices" }
mizer-node = { path = "../../../node" }
enum-iterator = "1.5"
num_enum = "0.7"
