[package]
name = "mizer-step-sequencer-nodes"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
mizer-node = { path = "../../../node" }
serde = { version = "1", features = ["derive"] }
enum-iterator = "2.0"
num_enum = "0.7"
