fn main() {
    println!("cargo:rerun-if-changed=protos");
    tonic_build::configure()
        .build_server(true)
        .compile_protos(
            &[
                "protos/appearance.proto",
                "protos/console.proto",
                "protos/connections.proto",
                "protos/fixtures.proto",
                "protos/layouts.proto",
                "protos/media.proto",
                "protos/nodes.proto",
                "protos/session.proto",
                "protos/sequencer.proto",
                "protos/effects.proto",
                "protos/transport.proto",
                "protos/programmer.proto",
                "protos/settings.proto",
                "protos/plans.proto",
                "protos/mappings.proto",
                "protos/timecode.proto",
                "protos/surfaces.proto",
                "protos/ui.proto",
            ],
            &["protos/"],
        )
        .unwrap();
}
