[package]
name = "mizer-audio-pipeline"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
uuid = { version = "1.16", features = ["v4"] }
mizer-node = { path = "../node" }
daggy = "0.9"
