[package]
name = "mizer-protocol-osc"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
rosc = "0.10"
log = "0.4"
flume = "0.11"
mizer-message-bus = { path = "../../../../util/bus" }
futures = "0.3"
mizer-module = { path = "../../../../runtime/module" }
mizer-commander = { path = "../../../../runtime/commander" }
tokio = { version = "1.36", features = ["net", "rt"] }
serde = { version = "1", features = ["derive"] }
