[package]
name = "mizer-console"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
tracing = "0.1"
mizer-module = { path = "../../runtime/module" }
mizer-message-bus = { path = "../../util/bus" }
flume = "0.11"
futures = "0.3"
parking_lot = "0.12.2"
chrono = "0.4"
