[package]
name = "mizer-webcam-nodes"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
tracing = "0.1"
mizer-node = { path = "../../../node" }
serde = { version = "1", features = ["derive"] }
enum-iterator = "2.0"
num_enum = "0.7"
mizer-wgpu = { path = "../../../../wgpu" }
image = "0.25"
profiling = "1"
mizer-webcams = { path = "../../../../../components/connections/devices/webcams" }
mizer-devices = { path = "../../../../../components/connections/devices" }
mizer-video-nodes = { path = ".." }
ringbuffer = "0.15"
