[package]
name = "mizer-remote-api"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
profiling = "1.0"
tracing = "0.1"
prost = "0.11"
prost-types = "0.11"
tonic = "0.9"
tokio = "1.29"
mizer-api = { path = ".." }

[build-dependencies]
tonic-build = "0.9"

