[package]
name = "mizer-ndi-nodes"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
tracing = "0.1"
mizer-node = { path = "../../../node" }
serde = { version = "1", features = ["derive"] }
mizer-wgpu = { path = "../../../../wgpu" }
image = "0.24"
profiling = "1"
ndi = { git = "https://github.com/maxjoehnk/ndi-rs.git", branch = "feature/ndi-5" }
futures = "0.3"
mizer-ndi = { path = "../../../../../components/connections/devices/ndi" }
mizer-devices = { path = "../../../../../components/connections/devices" }
mizer-video-nodes = { path = ".." }
ringbuffer = "0.15"
