[package]
name = "mizer-port-operation-nodes"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
log = "0.4"
mizer-node = { path = "../../../node" }
serde = { version = "1", features = ["derive"] }
bezier-rs = "0.1"
itertools = "0.10"
rand = "0.8"
mizer-util = { path = "../../../../../util" }

[dev-dependencies]
test-case = "2.2"
