[package]
name = "mizer-ui-ffi"
version = "0.1.0"
edition = "2021"

[lib]
name = "mizer_ui_ffi"
crate-type = ["cdylib", "lib"]

[features]
build-ffmpeg = ["ffmpeg-the-third/build"]

[dependencies]
pinboard = "2.2"
mizer-sequencer = { path = "../../components/sequencer" }
mizer-clock = { path = "../../runtime/clock" }
mizer-fixtures = { path = "../../components/fixtures" }
mizer-timecode = { path = "../../components/timecode" }
mizer-gamepads = { path = "../../components/connections/devices/gamepads" }
mizer-devices = { path = "../../components/connections/devices" }
mizer-node = { path = "../../runtime/pipeline/node" }
mizer-runtime = { path = "../../runtime" }
mizer-util = { path = "../../util" }
mizer-message-bus = { path = "../../util/bus" }
mizer-api = { path = "../../api" }
lazy_static = "1.4"
parking_lot = "0.12"
bitflags = "2.5"
ffmpeg-the-third = "3.0"
