[package]
name = "mizer-processing"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
dashmap = "5"
mizer-clock = { path = "../clock" }
mizer-injector = { path = "../injector" }

[dev-dependencies]
test-case = "2.2"
