[package]
name = "mizer-processing"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
mizer-clock = { path = "../clock" }
mizer-injector = { path = "../injector" }
mizer-debug-ui = { path = "../debug-ui" }

[dev-dependencies]
test-case = "3.1"
