[package]
name = "mizer-plan"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
log = "0.4"
dashmap = { version = "5", features = ["serde"] }
mizer-processing = { path = "../../runtime/processing" }
mizer-module = { path = "../../runtime/module" }
mizer-fixtures = { path = "../fixtures" }
mizer-commander = { path = "../../runtime/commander" }
mizer-util = { path = "../../util" }
profiling = "1"
serde = { version = "1", features = ["derive"] }
pinboard = "2.2"
itertools = "0.12"
uuid = { version = "1.5", features = ["serde"] }

[dev-dependencies]
test-case = "3.2"
