[package]
name = "mizer-fixture-nodes"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
tracing = "0.1"
serde = { version = "1", features = ["derive"] }
mizer-node = { path = "../../node" }
mizer-fixtures = { path = "../../../../components/fixtures" }
ringbuffer = "0.15"

[dev-dependencies]
mockall = "0.13"
mockall_double = "0.3"
predicates = "3.1"
test-case = "3.3"
