[package]
name = "mizer-video-nodes"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
log = "0.4"
mizer-node = { path = "../../node" }
gstreamer = "0.20"
gstreamer-video = "0.20"
gstreamer-gl = "0.20"
glib = "0.17"
lazy_static = "1.4"
serde = { version = "1", features = ["derive"] }
enum-iterator = "1.4"
num_enum = "0.6"
