[package]
name = "mizer-webcams"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
tracing = "0.1"
anyhow = "1"
futures = "0.3.30"
flume = "0.11"
pinboard = "2.2"
enum-iterator = "2.0"
nokhwa = { version = "0.10", features = ["input-native"] }
mizer-console = { path = "../../../console" }
