const double _GRID_BASE_SIZE = 15;
const double GRID_FINE_SIZE = _GRID_BASE_SIZE * 3;
const double GRID_ACTION_SIZE = _GRID_BASE_SIZE * 4;
const double GRID_MAIN_SIZE = _GRID_BASE_SIZE * 6;

const double NAVIGATION_BAR_SIZE = GRID_ACTION_SIZE;
const double PANEL_ACTION_SIZE = GRID_ACTION_SIZE;
const double TRANSPORT_CONTROLS_HEIGHT = GRID_FINE_SIZE;
const double PANEL_HEADER_HEIGHT = GRID_FINE_SIZE;
